/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SriSaiRouteImport } from './routes/sri-sai'
import { Route as SandyBeachRouteImport } from './routes/sandy-beach'
import { Route as SanEuphoriaRouteImport } from './routes/san-euphoria'
import { Route as SaiDurgaRouteImport } from './routes/sai-durga'
import { Route as PrakruthiRouteImport } from './routes/prakruthi'
import { Route as IndexRouteImport } from './routes/index'

const SriSaiRoute = SriSaiRouteImport.update({
  id: '/sri-sai',
  path: '/sri-sai',
  getParentRoute: () => rootRouteImport,
} as any)
const SandyBeachRoute = SandyBeachRouteImport.update({
  id: '/sandy-beach',
  path: '/sandy-beach',
  getParentRoute: () => rootRouteImport,
} as any)
const SanEuphoriaRoute = SanEuphoriaRouteImport.update({
  id: '/san-euphoria',
  path: '/san-euphoria',
  getParentRoute: () => rootRouteImport,
} as any)
const SaiDurgaRoute = SaiDurgaRouteImport.update({
  id: '/sai-durga',
  path: '/sai-durga',
  getParentRoute: () => rootRouteImport,
} as any)
const PrakruthiRoute = PrakruthiRouteImport.update({
  id: '/prakruthi',
  path: '/prakruthi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prakruthi': typeof PrakruthiRoute
  '/sai-durga': typeof SaiDurgaRoute
  '/san-euphoria': typeof SanEuphoriaRoute
  '/sandy-beach': typeof SandyBeachRoute
  '/sri-sai': typeof SriSaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prakruthi': typeof PrakruthiRoute
  '/sai-durga': typeof SaiDurgaRoute
  '/san-euphoria': typeof SanEuphoriaRoute
  '/sandy-beach': typeof SandyBeachRoute
  '/sri-sai': typeof SriSaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prakruthi': typeof PrakruthiRoute
  '/sai-durga': typeof SaiDurgaRoute
  '/san-euphoria': typeof SanEuphoriaRoute
  '/sandy-beach': typeof SandyBeachRoute
  '/sri-sai': typeof SriSaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prakruthi'
    | '/sai-durga'
    | '/san-euphoria'
    | '/sandy-beach'
    | '/sri-sai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prakruthi'
    | '/sai-durga'
    | '/san-euphoria'
    | '/sandy-beach'
    | '/sri-sai'
  id:
    | '__root__'
    | '/'
    | '/prakruthi'
    | '/sai-durga'
    | '/san-euphoria'
    | '/sandy-beach'
    | '/sri-sai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrakruthiRoute: typeof PrakruthiRoute
  SaiDurgaRoute: typeof SaiDurgaRoute
  SanEuphoriaRoute: typeof SanEuphoriaRoute
  SandyBeachRoute: typeof SandyBeachRoute
  SriSaiRoute: typeof SriSaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sri-sai': {
      id: '/sri-sai'
      path: '/sri-sai'
      fullPath: '/sri-sai'
      preLoaderRoute: typeof SriSaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandy-beach': {
      id: '/sandy-beach'
      path: '/sandy-beach'
      fullPath: '/sandy-beach'
      preLoaderRoute: typeof SandyBeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-euphoria': {
      id: '/san-euphoria'
      path: '/san-euphoria'
      fullPath: '/san-euphoria'
      preLoaderRoute: typeof SanEuphoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sai-durga': {
      id: '/sai-durga'
      path: '/sai-durga'
      fullPath: '/sai-durga'
      preLoaderRoute: typeof SaiDurgaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prakruthi': {
      id: '/prakruthi'
      path: '/prakruthi'
      fullPath: '/prakruthi'
      preLoaderRoute: typeof PrakruthiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrakruthiRoute: PrakruthiRoute,
  SaiDurgaRoute: SaiDurgaRoute,
  SanEuphoriaRoute: SanEuphoriaRoute,
  SandyBeachRoute: SandyBeachRoute,
  SriSaiRoute: SriSaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
